services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  YouzanApiDataBundle\Command\:
    resource: '../../Command/'
  YouzanApiDataBundle\Repository\:
    resource: '../../Repository/'
  YouzanApiDataBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']
  YouzanApiDataBundle\Service\:
    resource: '../../Service/'
